### PR TITLE
Add api version to MessengerClient

### PR DESCRIPTION
**Pull request by wittfabian**
#44

### CODE REVIEW

**Comment by rickydunlop** [comment]
Hey, thanks for this, could you update the default version to be 3.2 as it's the latest, then i'll get it merged

**Comment by wittfabian** [comment]
Hi, with 3.0 facebook has breaking changes with the sender_id.
So 2.12 is the last version with current sender_id support.

**Comment by rickydunlop** [comment]
What's the breaking changes? Have you got a link to the docs on it?

**Comment by wittfabian** [comment]
**Pages API**
> Page-Scoped ID API — On April 24th, 2018, we announced that the Pages API now returns Page-scoped User IDs instead of App-scoped User IDs. We have released a new, non-versioned API for developers who need to map App-scoped IDs to their Page-scoped ID equivalents.

https://developers.facebook.com/docs/graph-api/changelog/version3.0?locale=en_US

https://developers.facebook.com/docs/pages/access-tokens/psid-api

**Comment by rickydunlop** [comment]
From what I can tell the Messenger API's always returned page scoped IDs. 
This change was to update the Pages API so that it returned page scoped IDs instead of App scoped IDs. 
See this FAQ for info https://developers.facebook.com/docs/pages/access-tokens/psid-api/faq#faq_1181287948678652

Let's leave it for now and I can release the version update separately as a new major version just in case.

**Pull request merged**
